language: ruby
rvm:
  - 2.0.0
  - 2.1.0
before_install:
  - gem install bundler -v 1.6.6
  - cd source
install:
  - travis_retry bundle _1.6.6_ install --without debug
script:
  - bundle _1.6.6_ exec rake
gemfile:
  - gemfiles/minimal_release.gemfile
  - gemfiles/previous_release.gemfile
  - gemfiles/latest_stable.gemfile
