language: ruby
rvm:
- 1.9.3
- 2.0.0
- 2.1.0
before_install:
- cd source
install:
- travis_retry bundle install
- travis_retry appraisal install
script:
- bundle exec rake rubocop
- appraisal rake spec
- cd functional_tests && ./run_tests.sh
gemfile:
- Gemfile
- gemfiles/latest_stable.gemfile
- gemfiles/oldest_current.gemfile
- gemfiles/previous_release.gemfile
env:
  global:
  - OS_AUTH_URL: https://cloud.numergy.com/identity/v2.0/tokens
  - OS_NETWORK_URL: https://cloud.numergy.com/network/v2.0
  - OS_FLAVOR: 2_vCPU_RAM_4G_HD_10G
  - OS_FLOATING_IP: 185.39.216.103
  - OS_USERNAME: vagrant-openstack@numergy.com
  - OS_TENANT_NAME: Numergy-Dev:vagrant-openstack-plugin-test
  - secure: nb2YoZU7U3v79FCZSAlNbIEzxVzdXctBZlL3v0xLiAVofgx4jBvHaUwwiq1zhngjwAbLBm/l5tLH4aSaYVJwOxzIzRhWzsrjUg38j4Olssnti/quMe5F4FPC1qCYR5pcILizjKlOQWYEYSuQp6tnkogurvbYKB+JwTc9MFSbq80=
